package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscrambler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../IDL/WordUnscramblerApp.idl
* Sunday, May 9, 2021 7:28:39 PM CST
*/

public interface WordUnscrambler extends WordUnscramblerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordUnscrambler
