package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscramblerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../IDL/WordUnscramblerApp.idl
* Saturday, May 8, 2021 2:46:30 AM CST
*/

public interface WordUnscramblerOperations 
{
  boolean logIn (String username);
  String requestWord (String username);
  boolean checkAnswer (String username, String answer);
  String requestRescramble (String username);
} // interface WordUnscramblerOperations
