package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscramblerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordUnscramblerApp.idl/
* Thursday, May 6, 2021 8:30:22 AM CST
*/

public interface WordUnscramblerOperations 
{
  boolean logIn (String username);
  String requestWord ();
  boolean checkAnswer (String answer);
  String requestRescramble ();
} // interface WordUnscramblerOperations
