# Python stubs generated by omniidl from ..\IDL\WordUnscramblerApp.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WordUnscramblerApp"
#
__name__ = "WordUnscramblerApp"
_0_WordUnscramblerApp = omniORB.openModule("WordUnscramblerApp", r"..\IDL\WordUnscramblerApp.idl")
_0_WordUnscramblerApp__POA = omniORB.openModule("WordUnscramblerApp__POA", r"..\IDL\WordUnscramblerApp.idl")


# interface WordUnscrambler
_0_WordUnscramblerApp._d_WordUnscrambler = (omniORB.tcInternal.tv_objref, "IDL:WordUnscramblerApp/WordUnscrambler:1.0", "WordUnscrambler")
omniORB.typeMapping["IDL:WordUnscramblerApp/WordUnscrambler:1.0"] = _0_WordUnscramblerApp._d_WordUnscrambler
_0_WordUnscramblerApp.WordUnscrambler = omniORB.newEmptyClass()
class WordUnscrambler :
    _NP_RepositoryId = _0_WordUnscramblerApp._d_WordUnscrambler[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WordUnscramblerApp.WordUnscrambler = WordUnscrambler
_0_WordUnscramblerApp._tc_WordUnscrambler = omniORB.tcInternal.createTypeCode(_0_WordUnscramblerApp._d_WordUnscrambler)
omniORB.registerType(WordUnscrambler._NP_RepositoryId, _0_WordUnscramblerApp._d_WordUnscrambler, _0_WordUnscramblerApp._tc_WordUnscrambler)

# WordUnscrambler operations and attributes
WordUnscrambler._d_logIn = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordUnscrambler._d_requestWord = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
WordUnscrambler._d_checkAnswer = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
WordUnscrambler._d_requestRescramble = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
WordUnscrambler._d_requestScore = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
WordUnscrambler._d_getLeaderboardPosition = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)

# WordUnscrambler object reference
class _objref_WordUnscrambler (CORBA.Object):
    _NP_RepositoryId = WordUnscrambler._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def logIn(self, *args):
        return self._obj.invoke("logIn", _0_WordUnscramblerApp.WordUnscrambler._d_logIn, args)

    def requestWord(self, *args):
        return self._obj.invoke("requestWord", _0_WordUnscramblerApp.WordUnscrambler._d_requestWord, args)

    def checkAnswer(self, *args):
        return self._obj.invoke("checkAnswer", _0_WordUnscramblerApp.WordUnscrambler._d_checkAnswer, args)

    def requestRescramble(self, *args):
        return self._obj.invoke("requestRescramble", _0_WordUnscramblerApp.WordUnscrambler._d_requestRescramble, args)

    def requestScore(self, *args):
        return self._obj.invoke("requestScore", _0_WordUnscramblerApp.WordUnscrambler._d_requestScore, args)

    def getLeaderboardPosition(self, *args):
        return self._obj.invoke("getLeaderboardPosition", _0_WordUnscramblerApp.WordUnscrambler._d_getLeaderboardPosition, args)

omniORB.registerObjref(WordUnscrambler._NP_RepositoryId, _objref_WordUnscrambler)
_0_WordUnscramblerApp._objref_WordUnscrambler = _objref_WordUnscrambler
del WordUnscrambler, _objref_WordUnscrambler

# WordUnscrambler skeleton
__name__ = "WordUnscramblerApp__POA"
class WordUnscrambler (PortableServer.Servant):
    _NP_RepositoryId = _0_WordUnscramblerApp.WordUnscrambler._NP_RepositoryId


    _omni_op_d = {"logIn": _0_WordUnscramblerApp.WordUnscrambler._d_logIn, "requestWord": _0_WordUnscramblerApp.WordUnscrambler._d_requestWord, "checkAnswer": _0_WordUnscramblerApp.WordUnscrambler._d_checkAnswer, "requestRescramble": _0_WordUnscramblerApp.WordUnscrambler._d_requestRescramble, "requestScore": _0_WordUnscramblerApp.WordUnscrambler._d_requestScore, "getLeaderboardPosition": _0_WordUnscramblerApp.WordUnscrambler._d_getLeaderboardPosition}

WordUnscrambler._omni_skeleton = WordUnscrambler
_0_WordUnscramblerApp__POA.WordUnscrambler = WordUnscrambler
omniORB.registerSkeleton(WordUnscrambler._NP_RepositoryId, WordUnscrambler)
del WordUnscrambler
__name__ = "WordUnscramblerApp"

#
# End of module "WordUnscramblerApp"
#
__name__ = "WordUnscramblerApp_idl"

_exported_modules = ( "WordUnscramblerApp", )

# The end.
