package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscrambler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Lance/Desktop/9322-fingrp2/src/IDL/WordUnscramblerApp.idl
* Tuesday, May 18, 2021 7:01:54 PM CST
*/

public interface WordUnscrambler extends WordUnscramblerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordUnscrambler
