package WordUnscramblerApp;


/**
* WordUnscramblerApp/WordUnscrambler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Lance/Desktop/9322-fingrp2/src/IDL/WordUnscramblerApp.idl
* Friday, May 14, 2021 12:02:16 AM CST
*/

public interface WordUnscrambler extends WordUnscramblerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface WordUnscrambler
